# Generated by Django 4.0.4 on 2022-05-13 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('type', models.CharField(max_length=15)),
                ('brand', models.CharField(max_length=15)),
                ('year', models.PositiveSmallIntegerField()),
                ('condition', models.CharField(max_length=8)),
                ('place', models.CharField(max_length=20)),
                ('price', models.PositiveBigIntegerField()),
                ('img', models.ImageField(upload_to='post/')),
            ],
        ),
    ]
